config/routes.rb
Wikiclone::Application.routes.draw do

  resources :charges

  resources :wikis do 
    resources :collaborators
  end

  devise_for :users

  get "welcome/index"

  get "welcome/about"

  root to: 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user, not logged in

    # # if a member, they can: a) inherit permission of users (read all except private wikis), b)manage their own wikis, c) destroy their own wikis
    # if User.role? :member
    #   can :manage, Wiki, :user_id => user.id
    #   can :destroy, Wiki, :user_id => user.id
    # # Regular members can't create or read private wikis
    #   cannot :manage, Wiki, private => true
    # end

    # # if a premium member, they: a) inherit permissions of members, b) can create collaborators, c) destroy collaborators
    # if User.role? :premium_member
    #   can :create, Collaborators
    #   can :destroy, Collaborators
    #   #Premium members can create private wikis that only they and collaboratos can access
    #   can :manage, Wiki, private => true, user_id => user.id
    # end

    # # Admins can do anything
    # if User.role? :admin
    #   can :manage, :all
    # end

    # # All users can read any public wiki
    # can :read, Wiki, private => false

    # >>> Pasted

    # if a member, they can manage their own posts 
    # (or create new ones)
    if user.role? :member
      can :manage, Wiki, :user_id => user.id, :private => false
      cannot :manage, Wiki, :user_id => user.id, :private => true
      cannot :manage, @collaborators
      # can :manage, Wiki, :user_id => user.id
    end

    # Moderators can delete any post
    if user.role? :premium_member
      can :manage, Wiki, :user_id => user.id, :private => true
      can :manage, @collaborators
    end

    # Admins can do anything
    if user.role? :admin
      can :manage, :all
    end

    can :read, :all
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  attr_accessible :user_id, :wiki_id

  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :wikis
  has_many :collaborators

  # automatically assigns role of 'member' to each user who signs up.  set_member method lives below.
  before_create :set_member

  # Setting ROLES constant
  ROLES = %w[member premium_member admin]

  #defining role? method that Cancan will use for role-based permission system
	def role?(base_role)
  	role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
	end

	private

	# Sets the role of a user to 'member'
	def set_member
		self.role = 'member'
	end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title
  attr_accessible :body, :private, :title

  belongs_to :user
  has_many :collaborators

  #Checks whether user is a collaborator on the current wiki
  def has_collaborator?(user)
  	collaborators.where(user_id: user.id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	 # check if charge is present? 
	 # if so, update attribute on member to make premium
	 current_user.update_attribute(:role, 'premium_member') if charge

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_filter :get_wiki
  
  def new
  	@collaborator = Collaborator.new
  end

  def create
    authorize! :create, Collaborator
    @wiki.collaborators.destroy_all
    collaborators = []
    params[:collaborator][:user_id].each do |user_id|
      Rails.logger.info ">>>>> creating a collaborator"
      collaborators << Collaborator.create(wiki_id: @wiki.id, user_id: user_id)
    end
    Rails.logger.info ">>> #{Collaborator.all.inspect}"
    Rails.logger.info ">>>> #{@wiki.collaborators.inspect}"

    if collaborators.any?
      flash[:notice] = "Your collaborators have been added."
    else
      flash[:notice] = "You no longer have any collaborators on this wiki."
    end

    redirect_to @wiki
  end

  def show
  end

  def edit
  end

  private

  def get_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
	before_filter :set_wiki, only: [:edit, :show, :update, :destroy]

  def index
  	@wikis = Wiki.all
  end

  def show
    @collaborator = Collaborator.new
  end

  def new #page where form lives
  	@wiki = Wiki.new
  end

  def edit
  	authorize! :update, @wiki, message: "You are not authorized."
  	# show existing wiki object in a form
  end

  def create
  	# create wiki from form
  	@wiki = Wiki.new(params[:wiki])
  	@wiki.user = current_user
  	if @wiki.save
  		flash[:notice] = "your wiki was saved"
  		redirect_to @wiki #redirects to wiki that was just saved
  	else
  		flash[:error] = "Whoops!"
  		render :new #saves form information and pushes it back into displayed form
  	end
  end

  def update
  	# update existing wiki from form
  end

  def destroy
  end

  private 

  def set_wiki
  	@wiki = Wiki.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/collaborators/_form.html.erb
<% # [wiki, collaborator] defines post submit path (e.g. domain.com/wiki/[wiki_id/collaborator[collaborator_id] %>
<%= form_for [wiki, collaborator], html: { class: 'form-horizontal'} do |f| %>
	<% # User.all grabs all users %>
	<% User.all.each do |user| %>
		<% # "collaborator[user_id][]" tells Rails to push the user_id for this user into an hash called collaborator that gets pushed into the params hash; user.id populates the 'value' attribute of the checkbox element, has_collaborator? calls the has_collaborator? method in the wiki class which checks whether this user is marked as a collaborator on this wiki %>
		<p><%= check_box_tag "collaborator[user_id][]", user.id, wiki.has_collaborator?(user) %> <%= user.name %></p>
	<% end %>
	<%= f.submit "Save" %>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

app/views/collaborators/show.html.erb
<h1>Collaborators#show</h1>
<p>Find me in app/views/collaborators/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiclone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Home", welcome_index_path %></li>
			<li><%= link_to "About", welcome_about_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
		</ul>

		<% if flash[:notice] %>
      <div class="alert alert-success">
      	<button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="hero-unit">
	<h1>Wikiclone</h1>
	<p>Social, markdown wikis</p>
	<p><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>

</div>
<div class="row">
	<div class="span6">
		<p class="text-center">Create as many public wikis as you want!</p>
		<p class="text-center"><%= link_to "Free Plan", new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
	</div>
	<div class="span6">
		<p class="text-center">Create public wikis!</p>
		<p class="text-center"><%= link_to "Premium Plan", new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
	</div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki, html: { class: 'form-horizontal' } do |f| %>

	<%= control_group_tag(@wiki.errors[:title]) do %>
		<%= f.label :title, class: 'control-label' %>
		<div class="controls">
			<%= f.text_field :title %>
		</div>
	<% end %>
	<%= control_group_tag(@wiki.errors[:body]) do %>
		<%= f.label :body, class: 'control-label' %>
		<div class="controls">
			<%= f.text_area :body, rows: 8 %>
		</div>
	<% end %>
	<% if current_user.role? :premium_member %>
		<%= control_group_tag(@wiki.errors[:private]) do %>
			<%= f.label :private, class: 'control-label' %>
			<div class="controls">
				<%= f.check_box :private %>
			</div>
		<% end %>
	<% end %>
	<div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
	
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit <%= @wiki.title %></h1>
<%= render "form" %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<table>
	<tbody>
		<% @wikis.each do |wiki| %>
			<tr>
				<td><%= link_to wiki.title, wiki %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<%= render "form" %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true) %>
<p><%= raw markdown.render(@wiki.body).html_safe %></p>
<p><%= link_to "Edit Me", edit_wiki_path %></p>

<% if can? :manage, @collaborators %>
	<h3>Collaborators</h3>
	<%= render "collaborators/form", wiki: @wiki, collaborator: @collaborator %>
<% end %>